title: My Homepage on Gastro-Intestinal Cancer Research
author: William Waddingham
email: w.waddingham@ucl.ac.uk 
theme: minima 
description: Studying cancer precursor lesions in the stomach and oesophagus, to inform endoscopic surveillance strategies for early diagnosis.  

# social links
github_username:  wwaddingham


show_excerpts: true # set to false to remove excerpts on the homepage
